CREATE DATABASE bank_phase1;
DROP DATABASE bank_phase1;

USE bank_phase1;
SHOW TABLES;


CREATE DATABASE Bank_demo;
USE Bank_demo;

-- DROP DATABASE Bank_demo;

CREATE TABLE BRANCH (
    BID INT PRIMARY KEY,
    Name VARCHAR(100),
    Assets DECIMAL(15, 2),
    City VARCHAR(100),
    Address VARCHAR(255)
);

CREATE TABLE MANAGER (
	BID INT PRIMARY KEY,
    MANAGER INT
);

CREATE TABLE ASSISTANT_MGR(
	BID INT PRIMARY KEY,
    ASSISTANTMANAGER INT
);


CREATE TABLE EMPLOYEE (
    SSN INT PRIMARY KEY,
    Name VARCHAR(100),
    StartDate DATE,
    TeleNo VARCHAR(15),
    DependentName VARCHAR(100),
    BID INT
);

CREATE TABLE CUSTOMER (
    CSSN INT PRIMARY KEY,
    Name VARCHAR(100),
    City VARCHAR(100),
    State VARCHAR(100),
    Zipcode VARCHAR(10),
    StreetNo VARCHAR(10),
    AptNo VARCHAR(10)
);

/*
CREATE TABLE ACCOUNT (
    AccNo INT PRIMARY KEY,
    Balance DECIMAL(15, 2),
    Type VARCHAR(50),
    RecentAccess DATE,
    InterestsRate DECIMAL(5, 2),
    OverDraft DECIMAL(15, 2)
);
*/

CREATE TABLE ACCOUNT (
    AccNo INT PRIMARY KEY,
    Balance DECIMAL(15, 2),
    Type ENUM('Savings', 'Checking', 'Money Market', 'Loan'),
    RecentAccess DATE,
    InterestsRate DECIMAL(5, 2),
    OverDraft DECIMAL(15, 2)
);


CREATE TABLE ACC_OWNER (
    CSSN INT,
    AccNo INT,
    PRIMARY KEY (CSSN, AccNo)
);

CREATE TABLE TRANSACTION (
    TID INT,
    CSSN INT,
    AccNo INT,
    Code ENUM('WD', 'CD'),
    Date DATE,
    Time Time,
    Amount DECIMAL(15, 2),
    Charge DECIMAL(15, 2),
    PRIMARY KEY (TID, CSSN, AccNo)
);

CREATE TABLE PERSONAL_BANKER (
    CSSN INT,
    BID INT,
    ESSN INT,
    PRIMARY KEY (CSSN, BID, ESSN)
);

CREATE TABLE LOANS (
    CSSN INT,
    AccNo INT,
    BID INT,
    Amount DECIMAL(15, 2),
    LoanNo INT PRIMARY KEY,
    MonthlyRepayment DECIMAL(15, 2)
);




ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (BID) REFERENCES BRANCH(BID);

ALTER TABLE MANAGER
ADD FOREIGN KEY (Manager) REFERENCES EMPLOYEE(SSN);

ALTER TABLE ASSISTANT_MGR
ADD FOREIGN KEY (AssistantManager) REFERENCES EMPLOYEE(SSN);

ALTER TABLE ACC_OWNER
ADD FOREIGN KEY (CSSN) REFERENCES CUSTOMER(CSSN),
ADD FOREIGN KEY (AccNo) REFERENCES ACCOUNT(AccNo);

ALTER TABLE TRANSACTION
ADD FOREIGN KEY (CSSN) REFERENCES CUSTOMER(CSSN),
ADD FOREIGN KEY (AccNo) REFERENCES ACCOUNT(AccNo);

ALTER TABLE PERSONAL_BANKER
ADD FOREIGN KEY (CSSN) REFERENCES CUSTOMER(CSSN),
ADD FOREIGN KEY (BID) REFERENCES BRANCH(BID),
ADD FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE LOANS
ADD FOREIGN KEY (CSSN) REFERENCES CUSTOMER(CSSN),
ADD FOREIGN KEY (AccNo) REFERENCES ACCOUNT(AccNo),
ADD FOREIGN KEY (BID) REFERENCES BRANCH(BID);

select * from branch;
select * from employee;

