# Generated by Django 5.1.3 on 2024-11-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accno', models.IntegerField(db_column='AccNo', primary_key=True, serialize=False)),
                ('balance', models.DecimalField(blank=True, db_column='Balance', decimal_places=2, max_digits=15, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=12, null=True)),
                ('recentaccess', models.DateField(blank=True, db_column='RecentAccess', null=True)),
                ('interestsrate', models.DecimalField(blank=True, db_column='InterestsRate', decimal_places=2, max_digits=5, null=True)),
                ('overdraft', models.DecimalField(blank=True, db_column='OverDraft', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cssn', models.IntegerField(db_column='CSSN', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=10, null=True)),
                ('streetno', models.CharField(blank=True, db_column='StreetNo', max_length=10, null=True)),
                ('aptno', models.CharField(blank=True, db_column='AptNo', max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('bid', models.IntegerField(db_column='BID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('assets', models.DecimalField(blank=True, db_column='Assets', decimal_places=2, max_digits=15, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ssn', models.IntegerField(db_column='SSN', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('teleno', models.CharField(blank=True, db_column='TeleNo', max_length=15, null=True)),
                ('dependentname', models.CharField(blank=True, db_column='DependentName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=15, null=True)),
                ('loanno', models.IntegerField(db_column='LoanNo', primary_key=True, serialize=False)),
                ('monthlyrepayment', models.DecimalField(blank=True, db_column='MonthlyRepayment', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tid', models.IntegerField(db_column='TID', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=2, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=15, null=True)),
                ('charge', models.DecimalField(blank=True, db_column='Charge', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccOwner',
            fields=[
                ('cssn', models.OneToOneField(db_column='CSSN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='empApp.customer')),
            ],
            options={
                'db_table': 'acc_owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalBanker',
            fields=[
                ('cssn', models.OneToOneField(db_column='CSSN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='empApp.customer')),
            ],
            options={
                'db_table': 'personal_banker',
                'managed': False,
            },
        ),
    ]
